### ISSUE TITLE
Css-高度如何设置适应 屏幕大小 100%

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/css-content#11]
前景：高度背景  想要100%
![image](https://user-images.githubusercontent.com/53254347/124573445-226fdf00-de7c-11eb-8cba-e5de2883dd6e.png)

```css
.chart{
    background-color:#2D0889;
    position: absolute;
    min-height: 100%;
    width: 100%;
    left: 0;
    top: 0;
}
```
