### ISSUE TITLE
CSS-修改滚动条样式

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/css-content#12]
这几个要一起设置哦
```css
  ::-webkit-scrollbar {
    width: 7px;//宽度设置的是竖向滚动条的宽度
    height:7px //高度是设置横向滚动条的高度  
  }
  ::-webkit-scrollbar-track {
    border-radius: 7px;
    background-color: #fff;
  }
  ::-webkit-scrollbar-thumb {
    border-radius: 7px;
    background: rgba(0, 0, 0, 0.1);
  }
```
