### ISSUE TITLE
Css-实现一个从上到下的帘幕

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/css-content#20]
先看下样图：

![image](https://user-images.githubusercontent.com/53254347/200730306-47a7ca4a-8bb8-419f-992c-449424fd2a76.png)

有动画效果展开收起那种感觉，

### html层

主要分三层：

up-dialog：主体盖住全部

dialog-model：黑色半透明那个遮罩

dialog-content：主要内容

原理：

**up-dialog利用visibility显隐可以使用动画单纯地v-if 或者 react的if 会导致动画消失**

**dialog-model用opacity控制**

**dialog-content向上 还是向下动画利用transform**

```html
<View className={'up-dialog'} style={{visibility:showTimeFilter ? 'visible' : 'hidden'}}>
      <View className={'dialog-model'} onClick={()=>{ setShowTimeFilter(false)}} style={{opacity:showTimeFilter ? 1 : 0}}> </View>
      <View className={'dialog-content'} style={{transform:showTimeFilter ? 'translate3d(0,0,0)' : ''}}>
        <View className={'dialog-content-card'}>
          1231312
        </View>
      </View>
    </View>
```

```css
  .up-dialog{
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    z-index: 99;
    visibility: hidden;
    transition: visibility 300ms cubic-bezier(0.36, 0.66, 0.04, 1);
  }
  .dialog-model{
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    position: absolute;
    background-color: rgba(0,0,0,.3);
    transition: opacity 300ms ease-in;
  }
  .dialog-content{
    position: absolute;
    top: 0;
    width: 100%;
    height: 544px;
    background: #F8F8F8;
    border-radius: 0 0 20px 20px;
    padding: 30px;
    box-sizing: border-box;
    transform: translate3d(0,-100%,0);
    transition: transform 300ms cubic-bezier(.36,.66,.04,1);
  }
  .dialog-content-card{
    background: #fff;
  }
```

showTimeFilter 为true 显示  false隐藏帘幕
