### ISSUE TITLE
Css-自适应高度 transition失效-手风琴为例

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/css-content#21]
我们为了可以取出元素的自然高度，是将元素的height属性设置成auto的，
也就是说我们每次去取每次都设置为auto，
 但这样存在的一个问题就是：会覆盖前面的状态，
如果，一开始的height是0px, 然后你将height设置为200px, 
 这里两端都是明确的值，当然会发生过渡，
 但如果你为了取自然高度，在中间设置了一个auto，比如
先是height: 0px， 再height: auto, 再height: 200px;
这样，就是从auto 过渡到 200px, 由于auto不是确定的值，因此过渡不会发生

```js
import React, {useEffect, useState} from "react";
import './overtime-statistic.scss';
import {View} from "@tarojs/components";
import {AtIcon} from "taro-ui";
interface Props{}
const AccordionList: React.FC<Props> = () => {
  const [isShow, setIsShow] = useState(true);
  useEffect(()=>{

    const dom:any = document.getElementById('card-content');
    dom.dataset.height = dom.offsetHeight;
    dom.style.height = '0px'
    console.log(dom);
  },[])
  useEffect(()=>{
    const dom:any = document.getElementById('card-content');
    if(isShow){
      dom.style.height =  dom.dataset.height + 'px'
    }else{
      dom.style.height = '0px'
    }
  },[isShow])
  const iconClick = ()=>{
    setIsShow(!isShow)
  }
  return(
    <View className={'card-block mock_del'}>
      <View>
        我是头部
        <AtIcon
          className={isShow ? 'card-icon-rotate' : 'card-icon-no-rotate'}
          value='chevron-right' size='30'
          color='#999'
          onClick={() => {
            iconClick()
          }}
        />
      </View>

      <View className={isShow ? 'card-show card-content' : 'card-hide card-content'} id={'card-content'}>
        <View>1231312313</View>
        <View>1231312313</View>
        <View>1231312313</View>
        <View>1231312313</View>
        <View>1231312313</View>
        <View>1231312313</View>
        <View>1231312313</View>
        <View>1231312313</View>
      </View>
    </View>
  )
}
export default AccordionList;
```
```css
  .card-block{
    padding: 0 30px;
    background: #F9F9F9;
  }
  .card-content{
    overflow: hidden;
    margin-top: 20px;
    box-sizing: border-box;
    border-radius: 8px;
    color: #666;
    font-size: 24px;
    transition: 0.5s;
    height: auto;
  }
```
