### ISSUE TITLE
CSS-实现带圆角的渐变色的边框

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/css-content#24]
问题：border-image 和 border-radius 并不兼容

解决

```css
  .div{
    width: 284px;
    height: 48px;
    border-radius: 10px;
    position: relative;
    border: 0 ;
    padding: 1px 1px;//使用padding来给背景颜色
    border-image: linear-gradient(104deg, #5BD1EF 19%, #87D342 84%) 1.4;
    background-clip: content-box,border-box;
    background-image: linear-gradient(#fff, #fff), linear-gradient(104deg, #5BD1EF, #87D342);
    display: flex;
    align-items: center;
  }
```

需要给border 0 不然的话，safri浏览器 会显示无圆角的边框子

 缺点：背景无法透明,并且当前元素无法设置padding,设置的话会导致边框超级大
