### ISSUE TITLE
CSS-文字搞渐变色

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/css-content#25]
css 未提供文字渐变色属性，偏方 为 设置外层background为 白色，内层文字透明，背景色渐变色 
```css
    .text-gradient{
      -webkit-text-fill-color: transparent;
      background: linear-gradient(112deg, #55ADED 18%, #8669FF 63%, #CE4CEB 102%);
      -webkit-background-clip: text;
      background-clip: text;
      color: transparent;
    }
```
bg 也可以这样  
```css
   background: linear-gradient(to bottom, #F4F8FF, #D5E9FF,#419FFF);
```
