### ISSUE TITLE
CSS-解决el-select 多选tag内容过长需要...

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/css-content#26]
```css
  ::v-deep .el-select {
    .el-select__tags {
      .el-tag {
        // 注意这个inline-block 对卡片溢出隐藏很重要
        display: inline-block;
        // 解决单个tag文字过长溢出隐藏问题
        .el-select__tags-text {
          display: inline-block;
          max-width: 70px;
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
        }
        .el-icon-close {
          top: -6px;
          right: -4px;
        }
      }
    }
  }
```
