### ISSUE TITLE
CSS-elment-ui修改样式

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/css-content#27]
# el-dialog
```css
::v-deep .el-dialog{
  background:  url(~@/assets/images/szDialog/dialog_bg.png);
  background-size: 100% 100%;
}
::v-deep .el-dialog__header{
  padding: 15px 0 15px 20px;
}
::v-deep .el-dialog__body{
  padding-top: 10px;
  padding-bottom: 27px;
}
::v-deep .el-dialog__headerbtn{
  background:  url(~@/assets/images/szDialog/dialog_close.png);
  background-size: 100% 100%;
  width: 32px;
  height: 32px;
  top: -1px;
  right: -2px;
}
::v-deep .el-dialog__title{
  font-weight: 500;
  font-size: 18px;
  color: #ECFFFE;
}

::v-deep .el-dialog__close{
  display: none;
}
```
# el-pagination
```css
::v-deep .el-pagination .btn-next{
  background: transparent;
  border-radius: 2px;
  border: 1px solid #23478B;
  color: #8DB7DC;
  box-shadow: none;
}
::v-deep .el-pagination .el-pager li{
  background: rgba(0,50,53,0.3);
  border-radius: 2px;
  border: 1px solid rgba(48,253,255,0.5);
  color: #30FDFF;
  box-shadow: none;
  margin: 0 2px;
}
::v-deep .el-pagination .btn-prev{
  background: rgba(0,50,53,0.3);
  border-radius: 2px;
  border: 1px solid rgba(48,253,255,0.5);
  color: #30FDFF;
  box-shadow: none;
}
::v-deep .el-pagination .el-pager li:not(.disabled).active{
  background-color: #0080C2 !important;
  color: #DCF0FF !important;
}
::v-deep .el-pagination__goto{
  font-size: 14px;
  color: #30FDFF;
}
::v-deep .el-pagination__classifier{
  font-size: 14px;
  color: #30FDFF;
}

::v-deep .el-pagination .el-pager li.is-active{
  background: #1C9CA2;
  color: #fff;
}


::v-deep .el-pagination__total{
  color: #fff;
}
```
 ### popper中的样式需要设置专属的名 如 popper-class="search-map-pagination" 放在没有scoped得style中
```css
.search-map-pagination{
  border: 1px solid #0199AF !important;
  background: rgba(7,23,43,0.5) !important;
  .el-select-dropdown__wrap{
    background: rgba(0, 56, 64,0.8);
  }
  .el-select-dropdown__item{
    color: #fff;
    font-weight: 400;
    font-size: 14px;
  }
  .el-select-dropdown__item.selected{
    background: transparent;
    color: #00DFFF;
  }
  .el-select-dropdown__item.hover, .el-select-dropdown__item:hover{
    background: transparent;
    color: #00DFFF;
  }
}
```
# el-table
```css
::v-deep .el-table__empty-text{
  font-size: 14px;
  color: #fff;
}
  /deep/ .el-table__empty-block{
    border-top: 0 !important;
  }
::v-deep .el-table .el-table__header-wrapper th{
  background-color: rgba(5,41,48,0.7) !important;
  color: #B1FFFA;
  border-bottom: 0;
}
::v-deep .el-table .el-table__fixed-header-wrapper th{
  background-color:#F2F4F7 !important;
  color: #717A90 !important;
  font-weight: 600;
  font-size: 14px;
  border-bottom: 0;
}
::v-deep .el-table{
  background-color: transparent !important;
}
::v-deep .el-table tr{
  background-color: rgba(5,41,48,0.1);
}
::v-deep .el-table--striped .el-table__body tr.el-table__row--striped td.el-table__cell{
  background-color: rgba(5,41,48,0.5)
}
::v-deep .el-table .el-table__cell{
  color: #fff;
  border: 0;
}
::v-deep .el-table .el-table__body tr:nth-child(odd).el-table__row:hover > td {
  background-color: inherit !important;  /* 或者你想设置的任何颜色 */
}
::v-deep .el-table .el-table__body tr:nth-child(even).el-table__row:hover > td {
    background-color: #0b294a !important; /* 或者你想设置的任何颜色 */
  }
::v-deep .el-table__inner-wrapper::before{
  display: none;
}
```
# el-select
```css
  ::v-deep .el-select .el-input__inner{
    background: rgba(0,45,84,0.2);
    font-size: 14px;
    color: #ACDAFE;
    border: 1px solid #7CA9CB;
  }
  //三角
  ::v-deep .el-select .el-input .el-select__caret{
    color: #8DB7DC;
  }

```
### popver中得样式需要设置专属的名 如：popper-class="my-search-green-dialog"
```css
.my-search-green-dialog{
  border: 1px solid #0199AF !important;
  background: rgba(0, 56, 64,0.8) !important;
  .el-dropdown-menu{
    //background: transparent;
    background: rgba(0, 56, 64,0.8);
    padding: 0;
  }
  .el-select-dropdown__item.selected{
    background: transparent;
    color: #30FDFF;
  }
  .el-select-dropdown__item.hover, .el-select-dropdown__item:hover{
    background: transparent;
    color: #30FDFF;
  }
  .el-select-dropdown__item{
    color: #fff;
    font-weight: 400;
    font-size: 14px;
  }
  .popper__arrow{
    border-bottom-color:#8DB7DC!important;
  }
  .popper__arrow::after{
    border-bottom-color:#8DB7DC!important;
  }
  .el-popper__arrow{
    display: none;
  }
}
```
# el-date-picker: 开始结束时间选择版本
```css
.my-picker-green-dialog{
  .el-picker-panel__content{
    background: rgba(0,45,84,1) !important;
    color: #8DB7DC !important;
  }
  .el-picker-panel__icon-btn{
    color: #8DB7DC;
  }
  .el-date-range-picker__header{
    color: #8DB7DC;
  }
  .popper__arrow{
    display: none !important;
    border-bottom-color:#8DB7DC!important;
  }
  .el-date-table th{
    color: #8DB7DC;
  }
  .el-date-table td.in-range div{
   //background-color: #666;
  }
}
```
# el-input
```css
::v-deep .el-input__wrapper{
  box-shadow: none !important;
  border: 1px solid rgba(48,253,255,0.5) !important;
  background: rgba(0,50,53,0.3);
}
::v-deep .el-input__inner{
  background: rgba(0,45,84,0.2);
  font-size: 14px;
  color: #ACDAFE;
  border: 0;
}
```
# el-date-picker
```css
  /deep/ .el-input--prefix .el-input__inner{
    background: rgba(0,45,84,0.2);
    border: 1px solid #7CA9CB;
    color: #fff;
  }
```
单独class
```css
.sz-date-picker{
  background: rgba(0,45,84,1) !important;
  color: #8DB7DC !important;
  .el-picker-panel__icon-btn{
    color: #8DB7DC;
  }
  .el-date-range-picker__header{
    color: #8DB7DC;
  }
  .popper__arrow{
    display: none !important;
    border-bottom-color:#8DB7DC!important;
  }
  .el-date-table th{
    color: #8DB7DC;
  }
}
```
# el-checkbox
```css
::v-deep .el-checkbox__label{
  color: #fff;
}
::v-deep .el-checkbox__input.is-checked+.el-checkbox__label{
  color: #FFFFFF;
}
::v-deep .el-checkbox__input.is-checked .el-checkbox__inner{
  background-color: #30FDFF;
  border-color:#30FDFF;
}
::v-deep .el-checkbox__input.is-checked .el-checkbox__inner::after{
  border-color: #333;
}
```
# el-radio
```css
::v-deep .el-radio{
  color: #B3BDD0;
}
::v-deep .el-radio__input.is-checked+.el-radio__label{
  color: #fff;
}
::v-deep .el-radio__input.is-checked .el-radio__inner{
  border-color: #3489f9;
  background: #3489f9;
}
```
# 待定
```css
```
