### ISSUE TITLE
CSS-el-table内容过长显示tootips

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/css-content#28]
### el-table表格行有一个可使用的show-overflow-tooltip属性，它接受一个Boolean，为true时多余的内容会在 hover 时以 tooltip的形式显示出来。

```css
<el-table
  :data="tableData"
  tooltip-effect="dark myTooltips" // dark/light为自带的可选值，myTooltips为自定义样式
  style="width: 100%">
    <el-table-column
     prop="address"
     label="地址"
     show-overflow-tooltip>
 	</el-table-column>
</el-table>
 
 // 注意别用scoped,重新写一个style
<style lang="scss">
.myTooltips{ 
// 你想要的样式
max-width: 500px !important;
}
</style>
```

关键点在于    tooltip-effect="dark myTooltips" 设置样式  和show-overflow-tooltip设置开启
