### ISSUE TITLE
CSS- motion-path和 offset-path定制路径实现动画

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/css-content#4]
```html
<div class="platform ">
  <span class=" circle circle-left"></span>
  <span class="circle circle-right"></span>
</div>
```

```css
  body{
    background: #0C0C0C;
  }
  .circle{
    position: absolute;
    display: inline-block;
    width:15px;
    height: 15px;
    border-radius: 50px;
    /* background-color: aquamarine; */
    text-shadow: 0px 10px 20px #fff;
    /* background: #000; */
    background-image: radial-gradient(#cdffff 10%,#44e9f3);
    box-shadow:0px 2px 8px rgba(225,255,255,0.6);
  }
  .circle-right{
    left:-92px;
    top:-445px;
    motion-path: path("M1027.77,517h45.96s16.25,0.206,20.98,15c8.44,20.045,85.92,214,85.92,214s8.35,18.469,2,28c-5.59,8.4-25.98,8-25.98,8L779,783");

    offset-path: path("M1027.77,517h45.96s16.25,0.206,20.98,15c8.44,20.045,85.92,214,85.92,214s8.35,18.469,2,28c-5.59,8.4-25.98,8-25.98,8L779,783");
    animation: moveRight 8s linear infinite;

  }
  @keyframes moveRight {
    100% { motion-offset: 100%;}
    100% { offset-distance: 100%;}
  }
  .circle-left{
    left:-82px;
    top:-430px;
    motion-path: path("M376,502H330s-16.269.206-21,15c-6.938,14.045-86,214-86,214s-8.354,18.469-2,28c5.6,8.4,26,8,26,8H625");

    offset-path: path("M376,502H330s-16.269.206-21,15c-6.938,14.045-86,214-86,214s-8.354,18.469-2,28c5.6,8.4,26,8,26,8H625");
    animation: moveLeft 8s linear infinite;

  }
  @keyframes moveLeft {
    100% { motion-offset: 100%;}
    100% { offset-distance: 100%;}
  }
```
效果：两个小球再动
![image](https://user-images.githubusercontent.com/53254347/79710043-5baf4400-82f6-11ea-87b5-e635920b2f20.png)
